replicaCount: 1

config:
  inCluster: true
  inClusterContextName: "wavey-us-ord"
  enableHelm: true
  oidc:
    secret:
      create: false
      name: headlamp-oidc
    externalSecret:
      enabled: true
      name: headlamp-oidc
    issuerURL: "https://idp.wavey.io/internal"
    callbackURL: "https://k8s-us-ord.wavey.io/oidc-callback"
    validatorClientID: "QdLiUA5RC81Q9o9itEAnh4CummEBksZ3"
    validatorIssuerURL: "https://idp.wavey.io/internal"
    scopes: "openid,email,profile"
    usePKCE: true
    useCookie: true

clusterRoleBinding:
  create: true
  clusterRoleName: cluster-admin

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: haproxy
  annotations:
    haproxy.org/ssl-redirect: "true"
  hosts:
    - host: k8s-us-ord.wavey.io
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - k8s-us-ord.wavey.io

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  wavey.ai/ingress: "true"
