replicaCount: 1

config:
  inCluster: true
  inClusterContextName: "wavey-us-ord-internal"
  enableHelm: true
  oidc:
    secret:
      create: false
      name: headlamp-oidc
    externalSecret:
      enabled: true
      name: headlamp-oidc
    issuerURL: "https://idp.wavey.io/internal"
    callbackURL: "https://k8s-us-ord.wavey.io/oidc-callback"
    validatorClientID: "QdLiUA5RC81Q9o9itEAnh4CummEBksZ3"
    validatorIssuerURL: "https://idp.wavey.io/internal"
    scopes: "openid,email,profile"
    usePKCE: true
    useCookie: true

clusterRoleBinding:
  create: true
  clusterRoleName: cluster-admin

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: haproxy
  annotations:
    haproxy.org/ssl-redirect: "true"
    haproxy.org/frontend-config-snippet: |
      acl headlamp_old_cluster path_beg /c/wavey-us-ord
      http-request redirect code 302 location https://k8s-us-ord.wavey.io/c/wavey-us-ord-internal/login if headlamp_old_cluster
    haproxy.org/backend-config-snippet: |
      http-request del-header Authorization
      http-response add-header Set-Cookie "headlamp-auth-wavey-us-ord.0=; HttpOnly; Secure; SameSite=Strict; Path=/clusters/wavey-us-ord; Max-Age=0"
      http-response add-header Set-Cookie "headlamp-auth-wavey-us-ord.1=; HttpOnly; Secure; SameSite=Strict; Path=/clusters/wavey-us-ord; Max-Age=0"
      http-response add-header Set-Cookie "headlamp-auth-wavey-us-ord.2=; HttpOnly; Secure; SameSite=Strict; Path=/clusters/wavey-us-ord; Max-Age=0"
  hosts:
    - host: k8s-us-ord.wavey.io
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: headlamp-tls
      hosts:
        - k8s-us-ord.wavey.io

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  wavey.ai/ingress: "true"
